anchor_version = "0.17.0"

[programs.localnet]
maridrop = "AaKhDmJu1rD23TL9qkoP9MzsK5agmcUcFRkthMV9643g"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/aankor/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -t 1000000 tests/*.ts"
